- year: 2026
  role: "Program Co-Chair"
  event: "ChinaSys'26 Spring"

- year: 2025
  role: "Journal Reviewer"
  event: "ACM TOS, ACM TACO, IEEE TC"

- year: 2024
  role: "Journal Reviewer"
  event: "IEEE Transactions on Computers (TC)"

- year: 2024
  role: "Program Committee Member"
  event: "26th ACM SIGOPS ChinaSys Workshop"

- year: 2023
  role: "Program Committee Member"
  event: "10th ACM EuroSys PaPoc Workshop"

- year: 2022
  role: "Journal Reviewer"
  event: "IEEE Transactions on Cloud Computing"
